name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        target: [win-x86]
        include:
          - target: win-x86
            platform: win
            architecture: x86
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build CLI utilities
        shell: pwsh
        run: |
          msbuild /m /t:restore,cli\uupmediaconverter:publish,cli\uupdownload:publish,cli\uupmediaconverterdismbroker:publish /p:Platform=${{ matrix.architecture }} /p:RuntimeIdentifier=${{ matrix.platform }}-${{ matrix.architecture }} /p:PublishDir=${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}/CLI /p:PublishSingleFile=true /p:PublishTrimmed=false /p:Configuration=Debug UUPMediaCreator.sln
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.architecture }}
          path: ${{ github.workspace }}/artifacts/${{ matrix.platform }}-${{ matrix.architecture }}
